"""empty message

Revision ID: 218dedde3478
Revises: 
Create Date: 2019-06-16 18:18:20.154658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '218dedde3478'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject_categories',
    sa.Column('created_at', sa.DATE(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DATE(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subject_types',
    sa.Column('created_at', sa.DATE(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DATE(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('created_at', sa.DATE(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DATE(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('about', sa.Text(), nullable=False),
    sa.Column('habitat', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['subject_categories.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['subject_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subjects')
    op.drop_table('subject_types')
    op.drop_table('subject_categories')
    # ### end Alembic commands ###
